/**
 * Config Server for CDP Tests
 *
 * Serves config fixture files from data/fixtures/ directory
 * Fixtures are pre-existing files (not generated by tests)
 */

import * as http from 'http';
import * as fs from 'fs';
import * as path from 'path';

let server: http.Server | null = null;
// Path from tests/cdp/utils/ to data/fixtures/: ../../.. then data/fixtures
const FIXTURES_DIR = path.join(__dirname, '../../../data/fixtures');

/**
 * Start a simple HTTP server that serves config fixture files from data/fixtures/
 * @param port - Port to listen on
 * @param filename - Filename to serve (e.g., cdp-scrollstepsize-config.js)
 * @returns Promise with the server URL
 * @throws Error if file doesn't exist in fixtures directory
 */
export async function startConfigServer(
    port: number,
    filename: string
): Promise<string> {
    return new Promise((resolve, reject) => {
        const filePath = `/${filename}`;
        const fullPath = path.join(FIXTURES_DIR, filename);

        // Verify file exists before starting server
        if (!fs.existsSync(fullPath)) {
            reject(new Error(`Config fixture not found: ${fullPath}`));
            return;
        }

        server = http.createServer((req, res) => {
            // Remove query string for matching
            const urlPath = (req.url || '').split('?')[0];

            if (urlPath === filePath) {
                try {
                    const content = fs.readFileSync(fullPath, 'utf-8');
                    res.writeHead(200, { 'Content-Type': 'application/javascript' });
                    res.end(content);
                } catch (error) {
                    res.writeHead(500, { 'Content-Type': 'text/plain' });
                    res.end('500 Internal Server Error');
                }
            } else {
                res.writeHead(404, { 'Content-Type': 'text/plain' });
                res.end('404 Not Found');
            }
        });

        server.listen(port, '127.0.0.1', () => {
            resolve(`http://127.0.0.1:${port}${filePath}`);
        });

        server.on('error', reject);
    });
}

/**
 * Stop the config server
 */
export async function stopConfigServer(): Promise<void> {
    return new Promise((resolve) => {
        if (server) {
            server.close(() => {
                server = null;
                resolve();
            });
        } else {
            resolve();
        }
    });
}
