// All g-NNN placeholder keys. TypeScript errors (TS1117) on duplicate keys.
// To add a new key: append the next sequential entry here first, then use
// `"g-NNN" satisfies GKey` at every mapkey/mappings.add call site.
export const G_KEYS = {
    "g-001": "cmd_tab_detach",
    "g-002": "cmd_tab_next",
    "g-003": "cmd_tab_goto_index",
    "g-004": "cmd_nav_new_window",
    "g-005": "cmd_nav_new_incognito_window",
    "g-006": "cmd_bookmark_toggle_folder",
    "g-007": "cmd_bookmark_empty_folder",
    "g-008": "cmd_bookmark_lookup_url",
    "g-009": "cmd_bookmark_copy_folder_reversed",
    "g-010": "cmd_bookmark_copy_folder_ordered",
    "g-011": "cmd_bookmark_add_m",
    "g-012": "cmd_bookmark_remove_m",
    "g-013": "cmd_bookmark_cut_folder_reversed",
    "g-014": "cmd_bookmark_cut_folder_ordered",
    "g-015": "cmd_nav_clipboard_navigate",
    "g-016": "cmd_bookmark_save_youtube_position",
    "g-017": "cmd_bookmark_youtube_playlist",
    "g-018": "cmd_page_linkify",
    "g-019": "cmd_show_help",
    "g-020": "cmd_inspect_element",
    "g-021": "cmd_hints_open_incognito",
    "g-022": "cmd_tab_print_m",
    "g-023": "cmd_tab_group_collapse",
    "g-024": "cmd_tab_group_collapse_all",
    "g-025": "cmd_tab_group_expand_all",
    "g-026": "cmd_tab_quick_mark_save",
    "g-027": "cmd_tab_quick_mark_jump",
    "g-028": "cmd_tab_group_new_magic",
    "g-029": "cmd_tab_group_edit_name",
    "g-030": "cmd_tab_capture_mhtml",
    "g-031": "cmd_noop",
    "g-032": "cmd_yank_selection",
    "g-033": "cmd_download_open_last",
    "g-034": "cmd_download_show_last",
} as const;

export type GKey = keyof typeof G_KEYS;
